name: .NET

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  ArtifactName: Animals
  FilesDirectory: files
  WebAppName: TEAM-ox-2021

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      #gets the code from our branch
      - uses: actions/checkout@v2

      # sets up tooling for .NET
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore

      - name: Publish
        run: dotnet publish  --no-build --no-restore --output files

      - name: Test
        run: dotnet test AnimalAdoption.Web.Portal.UnitTests/AnimalAdoption.Web.Portal.UnitTests.csproj --no-build --verbosity normal

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.2.2
        with:
          # Artifact name
          name: ${{ env.ArtifactName }}
          # A file, directory or wildcard pattern that describes what to upload
          path: ${{ env.FilesDirectory }}
          # The desired behavior if no files are found using the provided path.
          if-no-files-found: error

  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download a Build Artifact
        uses: actions/download-artifact@v2.0.8
        with:
          # Artifact name
          name: ${{ env.ArtifactName }}
          # Destination path
          path: ${{ env.FilesDirectory }}

      - name: Azure Login
        uses: Azure/login@v1
        with:
          # Paste output of `az ad sp create-for-rbac` as value of secret variable: AZURE_CREDENTIALS
          creds: ${{ secrets.SECRET_SERVICE_PRINCIPAL }}

      - name: Azure WebApp
        uses: Azure/webapps-deploy@v2
        with:
          # Name of the Azure Web App
          app-name: ${{ env.WebAppName }}
          package: ${{ env.FilesDirectory }}
      - name: Azure key vault - Get Secrets
        uses: Azure/get-keyvault-secrets@v1
        with:
          # Name of the azure key vault
          keyvault: Team-Ox
          # Name of the secret to be fetched
          secrets: '*'
          
      - name: Azure App Service Settings
        uses: Azure/appservice-settings@v1
        with:
          # Name of the Azure Web App
          app-name: ${{ env.WebAppName }} 
          # Application settings using the JSON syntax set as value of secret variable: APP_SETTINGS
          app-settings-json: '[{ "name": "GlobalPassword", "value": $env.Global-Password }, { "name": "SimulatedFailureChance", "value": "0" }]'
            

