name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    #gets the code from our branch
    - uses: actions/checkout@v2
    
    # sets up tooling for .NET    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore
    - name: Publish
      run: dotnet publish --no-build --no-restore --output files
    #- name: Test
      #run: dotnet test --no-build --verbosity normal
      
      
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.2.2
      with:
        # Artifact name
        name: Animals
        # A file, directory or wildcard pattern that describes what to upload
        path: files
        # The desired behavior if no files are found using the provided path.
        if-no-files-found: error
    
    - name: Azure Login
      uses: Azure/login@v1
      with:
        # Paste output of `az ad sp create-for-rbac` as value of secret variable: AZURE_CREDENTIALS
        creds:  ${{ secrets.SECRET_SERVICE_PRINCIPAL }}
        # Set this value to true to enable Azure PowerShell Login in addition to Az CLI login
#         enable-AzPSSession: # optional
#         # Name of the environment. Supported values are azurecloud, azurestack, azureusgovernment, azurechinacloud, azuregermancloud. Default being azurecloud
#         environment: # optional, default is azurecloud
#         # Set this value to true to enable support for accessing tenants without subscriptions
#         allow-no-subscriptions: # optional
    

    - name: Azure WebApp
      uses: Azure/webapps-deploy@v2
      with:
        # Name of the Azure Web App
        app-name: TEAM-ox-2021
        # Enter an existing Slot other than the Production slot
        # slot-name: # optional, default is production
        # Applies to Web App only: Path to package or folder. *.zip, *.war, *.jar or a folder to deploy
        package: files
        # Applies to Web App Containers only: Specify the fully qualified container image(s) name. For example, 'myregistry.azurecr.io/nginx:latest' or 'python:3.7.2-alpine/'. For multi-container scenario multiple container image names can be provided (multi-line separated)
        #images: 
        # Applies to Web App Containers only: Path of the Docker-Compose file. Should be a fully qualified path or relative to the default working directory. Required for multi-container scenario
        #configuration-file: # optional
        # Enter the start up command. For ex. dotnet run or dotnet run
        #startup-command: # optional


