name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  ArtifactName: Animals
  FilesDirectory: files

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    #gets the code from our branch
    - uses: actions/checkout@v2
    
    # sets up tooling for .NET    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore
    
    - name: Publish
      run: dotnet publish  --no-build --no-restore --output files
    #- name: Test
      #run: dotnet test --no-build --verbosity normal
      
      
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.2.2
      with:
        # Artifact name
        name: ${{ env.ArtifactName }}
        # A file, directory or wildcard pattern that describes what to upload
        path: ${{ env.FilesDirectory }}
        # The desired behavior if no files are found using the provided path.
        if-no-files-found: error

    - name: Azure WebApp
      uses: Azure/webapps-deploy@v2
      with:
        # Name of the Azure Web App
        app-name: TEAM-ox-2021
        # Applies to Web Apps(Windows and Linux) and Web App Containers(linux). Multi container scenario not supported. Publish profile (*.publishsettings) file contents with Web Deploy secrets
        publish-profile: ${{ secrets.SECRET_PUBLISH_PROFILE }}
        # Enter an existing Slot other than the Production slot
        # slot-name: # optional, default is production
        # Applies to Web App only: Path to package or folder. *.zip, *.war, *.jar or a folder to deploy
        package: ${{ env.FilesDirectory }}
        # Applies to Web App Containers only: Specify the fully qualified container image(s) name. For example, 'myregistry.azurecr.io/nginx:latest' or 'python:3.7.2-alpine/'. For multi-container scenario multiple container image names can be provided (multi-line separated)
        #images: 
        # Applies to Web App Containers only: Path of the Docker-Compose file. Should be a fully qualified path or relative to the default working directory. Required for multi-container scenario
        #configuration-file: # optional
        # Enter the start up command. For ex. dotnet run or dotnet run
        #startup-command: # optional


